### ISSUE TITLE
When did you update the metric computation code?

### ISSUE THREAD

**Issue by Liusandian** [VCL3D/Pano3D#2]
Thank you for the open source code you contributed.In Boundary discontinuity preservation part and metrics computation,especially  About   Depth boundary errors of accuracy and completeness， I would like to ask if this part of the code can be released and updated in advance?Looking forward you reply ,thanks!

**Comment by tzole1155** [comment]
Hi Liusandian,

Thanks for your interest in our work.

We are going to release this part of the code quite soon, hopefully by the end of the week.

Best,

Giorgos

**Comment by Liusandian** [comment]
这是来自QQ邮箱的假期自动回复邮件。   谢谢你的来信,我会尽快给你回复。

**Comment by Liusandian** [comment]
> Hi Liusandian,
> 
> Thanks for your interest in our work.
> 
> We are going to release this part of the code quite soon, hopefully by the end of the week.
> 
> Best,
> 
> Giorgos
Hi Giorgos,
Thank you for your prompt reply. It's the weekend this week. As discussed before，would you please updated the code of Depth boundary errors of accuracy and completeness today or tomorrow? Looking forward to your reply, thanks again!

Best,
Liusandian

**Comment by Liusandian** [comment]
> Hi Liusandian,
> 
> Thanks for your interest in our work.
> 
> We are going to release this part of the code quite soon, hopefully by the end of the week.
> 
> Best,
> 
> Giorgos
Hi Giorgos,
Thank you for the open source code you contributed, and I want to ask another question. When calculating the metric, DbeCom and DbeAcc have 2 inputs, gt edge and pred edges, how should I get these two param from origin pred depth results, Should  I use structured edges to get extracted  edges?Looking forward to your reply, thanks!

**Comment by tzole1155** [comment]
Hi Liusandian,

We used the canny filter from the skimage package.

I'll upload also this code, so you could use it.

Best,

Giorgos

**Comment by Liusandian** [comment]
>
